# Generated by Django 3.2.6 on 2021-08-12 11:21

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(blank=True, default='2020-10-10', null=True, verbose_name=django.contrib.auth.models.AbstractUser)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=django.contrib.auth.models.AbstractUser)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name=django.contrib.auth.models.AbstractUser)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name=django.contrib.auth.models.AbstractUser)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True, verbose_name=django.contrib.auth.models.AbstractUser)),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True, verbose_name=django.contrib.auth.models.AbstractUser)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name=django.contrib.auth.models.AbstractUser)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name=django.contrib.auth.models.AbstractUser)),
                ('password', models.CharField(max_length=50, verbose_name=django.contrib.auth.models.AbstractUser)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name=django.contrib.auth.models.AbstractUser)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
